# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 22:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20160613_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='expiring_date',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 14, 22, 4, 31, 266723, tzinfo=utc), help_text='release date', null=True),
        ),
    ]
